apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-religion-quotes-service-deployment
  annotations:
    commitID: "744caf04a43615b76f864e436aeba0133f3a0b7e"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-religion-quotes-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: bad-religion-quotes-service
    spec:
      containers:
        - name: bad-religion-quotes-service
          image: 'xavelo/bad-religion-quotes-service:744caf04a43615b76f864e436aeba0133f3a0b7e'
          ports:
            - containerPort: 80
