apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-app-deployment
  annotations:
    commitID: "f9b5d841beb3acaccd55786891bdb1344fd2ba61"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: template-app
    spec:
      containers:
        - name: template-app
          image: 'xavelo/template-app-spring-boot:f9b5d841beb3acaccd55786891bdb1344fd2ba61'
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-template-app-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-template-app-secret
                  key: password
          ports:
            - containerPort: 80
