apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-app-deployment
  annotations:
    commitID: "1e5cef0cf04511b59164aa331ec3c805ab3a4c17"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: template-app
    spec:
      containers:
        - name: template-app
          image: 'xavelo/template-app-spring-boot:1e5cef0cf04511b59164aa331ec3c805ab3a4c17'
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-template-app-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-template-app-secret
                  key: password
          ports:
            - containerPort: 80
