apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-app-deployment
  annotations:
    commitID: "04056ea0bc8fc48fe55907563266ecaeb5d36a6a"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: template-app
    spec:
      containers:
        - name: template-app
          image: 'xavelo/template-app-spring-boot:04056ea0bc8fc48fe55907563266ecaeb5d36a6a'
          ports:
            - containerPort: 80
