apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-api-deployment
  annotations:
    commitID: "4fc02f19954eb3c016ab681114ddc31aeba9c3d0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: template-api
    spec:
      containers:
        - name: template-api
          image: 'xavelo/template-api-spring-boot:4fc02f19954eb3c016ab681114ddc31aeba9c3d0'
          ports:
            - containerPort: 80
