apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-api-deployment
  annotations:
    commitID: "f40107293ae580b9fe7c6e2db6007b0ba9c7a37e"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: template-api
    spec:
      containers:
        - name: template-api
          image: 'xavelo/template-api-spring-boot:f40107293ae580b9fe7c6e2db6007b0ba9c7a37e'
          ports:
            - containerPort: 80
