apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-app-deployment
  annotations:
    commitID: "2741cfe67678fd41653370ebe4032e5d23de23b9"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: template-app
    spec:
      containers:
        - name: template-app
          image: 'xavelo/template-app-spring-boot:2741cfe67678fd41653370ebe4032e5d23de23b9'
          ports:
            - containerPort: 80
