apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-api-deployment
  annotations:
    commitID: "04056ea0bc8fc48fe55907563266ecaeb5d36a6a"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: template-api
    spec:
      containers:
        - name: template-api
          image: 'xavelo/template-api-spring-boot:04056ea0bc8fc48fe55907563266ecaeb5d36a6a'
          ports:
            - containerPort: 80
